name: Feature Request
description: Suggest a new tool or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the tool or change you'd like
      placeholder: |
        Tool name: `do_something`
        GitLab API endpoint: `POST /projects/:id/...`
        Parameters: ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?

  - type: dropdown
    id: scope
    attributes:
      label: Tool Category
      description: Which area does this feature belong to?
      options:
        - Projects / Groups
        - Merge Requests
        - Issues
        - Pipelines / Jobs
        - Files / Repository
        - Branches
        - Labels
        - Users
        - Releases
        - Milestones
        - Wiki
        - Snippets
        - Search
        - Security / Config
        - New Category
    validations:
      required: true

  - type: dropdown
    id: gitlab_api
    attributes:
      label: GitLab API Reference
      description: Does this correspond to an existing GitLab REST API endpoint?
      options:
        - "Yes - documented in GitLab API docs"
        - "No - new behavior / aggregation"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information, API docs links, or examples
